name = "JSONWebTokens"
uuid = "9b8beb19-0777-58c6-920b-28f749fee4d3"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
version = "1.1.2-dev"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
JSON = "0.21"
MbedTLS = "1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
